using UnityEngine;
using UnityEngine.EventSystems;

public class GlobalUIFixer : MonoBehaviour
{
    private void Awake()
    {
        // 1. S'assurer qu'un EventSystem existe dans la scène
        EnsureEventSystemExists();
        
        // 2. On rend cet objet persistant pour qu'il répare chaque scène
        DontDestroyOnLoad(gameObject);
    }

    private void OnLevelWasLoaded(int level)
    {
        EnsureEventSystemExists();
    }

    // Version plus moderne pour les nouvelles versions d'Unity
    private void OnEnable()
    {
        UnityEngine.SceneManagement.SceneManager.sceneLoaded += OnSceneLoaded;
    }

    private void OnDisable()
    {
        UnityEngine.SceneManagement.SceneManager.sceneLoaded -= OnSceneLoaded;
    }

    private void OnSceneLoaded(UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode)
    {
        EnsureEventSystemExists();
    }

    private void EnsureEventSystemExists()
    {
        if (FindObjectOfType<EventSystem>() == null)
        {
            Debug.Log("GlobalUIFixer: EventSystem manquant détecté. Création d'un nouvel EventSystem.");
            
            GameObject eventSystem = new GameObject("EventSystem_AutoGenerated");
            eventSystem.AddComponent<EventSystem>();
            eventSystem.AddComponent<StandaloneInputModule>();
            
            // On le rend aussi persistant pour être tranquille
            DontDestroyOnLoad(eventSystem);
        }
    }
}
